language: node_js
node_js:
  - 'node'
cache:
  directories:
    - node_modules
script:
  - yarn test
  - yarn lint
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  target-branch: master
  on:
    branch: develop